using System.ComponentModel.DataAnnotations.Schema;
using MagitekApi.Enumerations;

namespace MagitekApi.Models
{
    [Table("ScholarSettings")]
    public class ScholarSettings : MagitekSettings
    {   
        public bool PrioritizeTankBusters { get; set; } 
        public bool DoTankBusters { get; set; }
        public bool UseAutoPreBuff { get; set; }
        public bool LucidDreaming { get; set; }
        public float LucidDreamingManaPercent { get; set; }
        public bool LucidDreamingOnlyWhenNoAetherFlow { get; set; }
        public bool ClericStance { get; set; }
        public bool Largesse { get; set; }
        public float LargesseHealthPercent { get; set; }
        public bool LargesseTank { get; set; }
        public bool LargesseDps { get; set; }
        public bool LargesseHealer { get; set; }
        public ChainStrategemStrategemStrategy ChainStrategemsStrategy { get; set; }
        public float InterruptHealingPercent { get; set; }     
        public bool InterruptHealing { get; set; }       
        public bool Protect { get; set; }
        public bool ProtectInCombat { get; set; }
        public bool ResOutOfCombat { get; set; }        
        public bool SwiftcastRes { get; set; }
        public bool RaiseFromOverlay { get; set; }
        public bool Physick { get; set; }
        public float PhysickHpPercent { get; set; }
        public bool Adloquium { get; set; }
        public float AdloquiumHpPercent { get; set; }
        public bool AdloquiumOnlyTankHealer { get; set; }
        public bool AdloquiumTankForBuff { get; set; }
        public bool Lustrate { get; set; }
        public float LustrateHpPercent { get; set; }
        public bool LustrateOnlyTankHealer { get; set; }
        public bool Succor { get; set; }
        public float SuccorHpPercent { get; set; }
        public int SuccorNeedHealing { get; set; }
        public bool SacredSoil { get; set; }
        public float SacredSoilHpPercent { get; set; }
        public int SacredSoilNeedHealing { get; set; }
        public bool Indomitability { get; set; }
        public float IndomitabilityHpPercent { get; set; }
        public int IndomitabilityNeedHealing { get; set; }
        public bool EmergencyTactics { get; set; }
        public bool EmergencyTacticsAdloquium { get; set; }
        public bool EmergencyTacticsSuccor { get; set; }
        public float EmergencyTacticsAdloquiumHealthPercent { get; set; }
        public float EmergencyTacticsSuccorHealthPercent { get; set; }
        public bool DeploymentTactics { get; set; }
        public bool DeploymentTacticsOnlyBoth { get; set; }
        public int DeploymentTacticsTimeLeft { get; set; }
        public int DeploymentTacticsAllyInRange { get; set; }
        public bool DeploymentTacticsEyeOnlyAfterAdlo { get; set; }
        public bool Excogitation { get; set; }
        public bool ExcogitationKeepUpOnTank { get; set; }
        public bool ExcogitationDoNotPhysickOrAdloquium { get; set; }
        public bool Dispel { get; set; }
        public bool DispelOnlyAbove { get; set; }
        public float DispelOnlyAboveHealth { get; set; }
        public bool DispelPet { get; set; }
        public bool AutomaticallyDispelAnythingThatsDispellable { get; set; }
        public bool UseTimeTillDeathForDots { get; set; }
        public bool UseTimeTillDeathForAoe { get; set; }
        public int DontDotIfEnemyDyingWithin { get; set; }
        public int DontAoeIfEnemyDyingWithin { get; set; }
        public bool DoDamage { get; set; }
        public bool StopCastingIfBelowHealthPercent { get; set; }
        public float DamageOnlyIfAboveHealthPercent { get; set; }
        public float MinimumManaPercent { get; set; }
        public bool ShadowFlare { get; set; }
        public int ShadowFlareEnemies { get; set; }
        public int ShadowFlareMinimumHealth { get; set; }
        public float ShadowFlareMinimumHealthPercent { get; set; }
        public int DotHealthMinimum { get; set; }
        public float DotHealthMinimumPercent { get; set; }
        public int DotRefreshSeconds { get; set; }
        public bool Bio { get; set; }
        public bool Miasma { get; set; }
        public bool Bane { get; set; }
        public int BaneSecondsOnDots { get; set; }
        public int BaneEnemies { get; set; }
        public bool EyeForAnEye { get; set; }
        public int EyeForAnEyeTankHealth { get; set; }
        public bool EyeForAnEyeAdloAfter { get; set; }
        public bool RuinBroil { get; set; }
        public bool Ruin2 { get; set; }
        public bool EnergyDrain { get; set; }
        public float EnergyDrainManaPercent { get; set; }
        public bool EnergyDrainUseAetherflowOffCooldown { get; set; }
        public bool Miasma2 { get; set; }
        public int Miasma2Enemies { get; set; }
        public int Miasma2HealthMinimum { get; set; }
        public float Miasma2HealthMinimumPercent { get; set; }
        public bool PetDontResummonInCombat { get; set; }
        public bool UsePet { get; set; }
        public ScholarPets SelectedPet { get; set; }
        public bool ScholarControlPet { get; set; }
        public bool Embrace { get; set; }
        public float EmbraceHpPercent { get; set; }
        public bool WhisperingDawn { get; set; }
        public int WhisperingDawnNeedHealing { get; set; }
        public float WhisperingDawnHealthPercent { get; set; }
        public bool FeyCovenant { get; set; }
        public float FeyCovenentHpPercent { get; set; }
        public bool FeyIllumination { get; set; }
        public float FeyIlluminationHpPercent { get; set; }
        public bool SilentDusk { get; set; }
        public bool FeyCaress { get; set; }
        public bool FeyWind { get; set; }
        public bool Rouse { get; set; }
        public float RouseHpPercent { get; set; }
        public bool RouseOnlyTankHealer { get; set; }
        public bool HealPartyMembersPets { get; set; }
        public bool HealPartyMembersPetsTitanOnly { get; set; }
        public bool Aetherpact { get; set; }
        public int AetherpactMinimumFairieGauge { get; set; }
        public float AetherpactHealthPercent { get; set; }
        public float AetherpactPhysickHealthPercent { get; set; }
        public bool AetherpactUseAdloquium { get; set; }
        public float AetherpactAdloquiumHealthPercent { get; set; }
        public bool IgnoreAlliance { get; set; }
        public bool HealAllianceHealers { get; set; }
        public bool HealAllianceTanks { get; set; }
        public bool HealAllianceDps { get; set; }
        public bool ResAllianceHealers { get; set; }
        public bool ResAllianceTanks { get; set; }
        public bool ResAllianceDps { get; set; }
        public bool HealAllianceOnlyPhysick { get; set; }
    }
}
